triburch_backend_juegos:
    resource: "@TriburchBackendJuegosBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/Triburch
    requirements:
            _locale: en|es|ca


da_wpepe:
    resource: "@DAWpepeBundle/Resources/config/routing.yml"
    prefix:   /

