triburch_backend_juegos:
    resource: "@TriburchBackendJuegosBundle/Resources/config/routing.yml"
    prefix:   /Triburch/{_locale}
    requirements:
            _locale: en|es_ES|ca


da_wpepe:
    resource: "@DAWpepeBundle/Resources/config/routing.yml"
    prefix:   /

