triburch_backend_juegos_Juegos:
    resource: "@TriburchBackendJuegosBundle/Resources/config/entitity_routing/Jocs.yml"
    prefix: /Jocs

triburch_backend_juegos_Categorias:
    resource: "@TriburchBackendJuegosBundle/Resources/config/entitity_routing/Categorias.yml"
    prefix: /Categorias

triburch_backend_juegos_Partida:
    resource: "@TriburchBackendJuegosBundle/Resources/config/entitity_routing/Partidas.yml"
    prefix: /Partidas

triburch_backend_juegos_Jugadors:
    resource: "@TriburchBackendJuegosBundle/Resources/config/entitity_routing/Jugadors.yml"
    prefix: /Jugadors

triburch_backend_juegos_Empresas:
    resource: "@TriburchBackendJuegosBundle/Resources/config/entitity_routing/Empresas.yml"
    prefix: /Empresas

traductor_new:
     path:     /Traductor/new/{id}
     defaults: { _controller: TriburchBackendJuegosBundle:Traductor:new }


