parameters:
#    triburch_backend_juegos.example.class: Triburch\Backend\JuegosBundle\Example

services:
#    triburch_backend_juegos.example:
#        class: %triburch_backend_juegos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
