<?php

namespace Triburch\Backend\JuegosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PartidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartidaRepository extends EntityRepository
{
}
