control_futbol_new:
    path:     Jugador/new/{_format}
    defaults: { _controller: ControlFutbolBundle:Jugador:new,_format: html }
    requirements: {_format: html|xml|json }


control_futbol_edit:
    path:     Jugador/edit/{id}/{_format}
    defaults: { _controller: ControlFutbolBundle:Jugador:edit,_format: html }
    requirements: {_format: html|xml|json }


control_futbol_delete:
    path:     Jugador/erase/{id}/{_format}
    defaults: { _controller: ControlFutbolBundle:Jugador:erase,_format: html}
    requirements: {_format: html|xml|json }


control_futbol_show:
    path:     Jugador/show/{id}/{_format}
    defaults: { _controller: ControlFutbolBundle:Jugador:show,_format: html }
    requirements: {_format: html|xml|json }

control_futbol_showall:
    path:     Jugador/list/{_format}
    defaults: { _controller: ControlFutbolBundle:Jugador:showall,_format: html }
    requirements: {_format: html|xml|json }

