<?php

namespace DAW\pepeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlumneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlumneRepository extends EntityRepository
{
}
