da_wpepe_homepage:
    path:     /hello/{name}
    defaults: { _controller: DAWpepeBundle:Default:index }


articulos:
  path: /articulos
  defaults: { _controller: DAWpepeBundle:Default:articulos }



articulo:
  path: /articulo/{id}
  defaults: { _controller: DAWpepeBundle:Default:articulo }


#CRUD BD
articulo_listar:
    path:  /articulos/list
    defaults: { _controller: DAWpepeBundle:Articulos:list }

articulo_crear:
    path:  /articulos/new
    defaults: { _controller: DAWpepeBundle:Articulos:new }



articulo_editar:
    path:  /articulos/edit/{id}
    defaults: { _controller: DAWpepeBundle:Articulos:edit }

articulo_visualizar:
    path:  /articulos/show/{id}
    defaults: { _controller: DAWpepeBundle:Articulos:show }

articulo_borrar:
    path:  /articulos/erase/{id}
    defaults: { _controller: DAWpepeBundle:Articulos:erase }


pr1:
    path:     /pr1/{string}
    defaults: { _controller: DAWpepeBundle:pr1:pr1 }
